[inputs]
# input directory with the files
dir = "inputs"

[inputs.res_profile]
# input files for data
file_list_of_file = "list_of_files_to_scale.csv"
file_name         = "ninja_pv_country_NL_merra-2_corrected.csv"
header_row        = 3
time_column_key   = "time"
data_column_key   = "national"

[inputs.target_values]
file_name         = "target_cp_national_ninja_pv_country_NL_merra-2_corrected.csv"
header_row        = 1
year_column_key   = "year"

[outputs]
dir = "outputs"
display_plot = false
first_hour_to_plot = 4380
last_hour_to_plot = 4548